<?php

namespace Tests\Feature;

use App\Book;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BookTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAsAdmin();
    }

    /** @test */
    public function onlyLoggedUserCanGetInformation()
    {
        $response = $this->get('api/auth/book')->assertStatus(200);
    }

    /** @test */
    public function authenticatedUsersCanGetBookInformation()
    {
        $response = $this->get('api/auth/book');

        $response->assertOk();
    }

    /** @test */
    public function creatingBookAfterAuthenticated()
    {
        $response = $this
            ->post('/api/auth/book', $this->data())->assertStatus(201);
    }

    /** @test */
    public function updateCount()
    {
        $response = $this
            ->post('/api/auth/book', ['title' => 'Clean Code']);

        $response->assertStatus(201);
    }

    public function actingAsAdmin()
    {
        $this->actingAs(factory(User::class)->create(['email'=>'admin@atlantico.com']));
    }

    private function data()
    {
        return [
            'title' => 'Clean Code'
        ];
    }
}
