<?php

namespace Tests\Feature;

use App\RentedBook;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class RentedBookTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAsAdmin();
    }

    /** @test */
    public function onlyLoggedUserCanGetInformation()
    {
        $response = $this->get('api/auth/rented_books')->assertRedirect('/api/unauthorized');
    }

    /** @test */
    public function authenticatedUsersCanGetRentedBooksInformation()
    {
        $response = $this->get('api/auth/rented_books')->assertOk();
    }

    /** @test */
    public function creatingRentForABookAfterAuthenticated()
    {



        $response = $this
            ->post('/api/auth/rented_books', ['book_id'])->assertStatus(201);
    }

    /** @test */
    public function emailIsUnique()
    {

        $response = $this
            ->post('/api/auth/user', array_merge($this->data(), ['email'=>'admin@atlantico.com']));

        $response->assertStatus(400);
    }

    public function actingAsAdmin()
    {
        $this->actingAs(factory(User::class)->create(['email'=>'admin@atlantico.com']));
    }

    public function dataForBook()
    {

    }

    public function dataForUser()
    {

    }
}
